services:
  palmr:
    image: kyantech/palmr:latest
    container_name: palmr
    environment:
      - ENABLE_S3=false
      - ENCRYPTION_KEY=change-this-key-in-production-min-32-chars # CHANGE THIS KEY FOR SECURITY
      # IMPORTANT: Set these to match your host user/group (run 'id' command to find yours)
      # Palmr defaults to UID 1001, but most Linux systems use UID 1000
      - PALMR_UID=1000 # Replace with your UID (from 'id' command)
      - PALMR_GID=1000 # Replace with your GID (from 'id' command)
    ports:
      - "5487:5487" # Web port
      - "3333:3333" # API port (OPTIONAL EXPOSED - ONLY IF YOU WANT TO ACCESS THE API DIRECTLY)
    volumes:
      # Bind mount for persistent data (uploads, database, temp files)
      - ./data:/app/server # Volume for the application data
    restart: unless-stopped # Restart the container unless it is stopped
