services:
  postgres:
    image: bitnami/postgresql:17.2.0
    container_name: palmr-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=palmr
      - POSTGRESQL_PASSWORD=palmr123
      - POSTGRESQL_DATABASE=palmr
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "palmr"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
