services:

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=palmr
      - MINIO_ROOT_PASSWORD=palmr123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: bitnami/postgresql:17.2.0
    container_name: palmr-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=palmr
      - POSTGRESQL_PASSWORD=palmr123
      - POSTGRESQL_DATABASE=palmr
    volumes:
      - postgres_data:/bitnami/postgresql
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "palmr"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
